// <auto-generated />
using System;
using Application.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Application.Migrations
{
    [DbContext(typeof(SessionContext))]
    partial class SessionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.13");

            modelBuilder.Entity("Application.Models.Session", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("TEXT")
                        .HasColumnName("created");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_change");

                    b.Property<int>("SessionType")
                        .HasColumnType("INTEGER")
                        .HasColumnName("session_type");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("Application.Models.Tab", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int?>("Tab")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("Tab");

                    b.ToTable("Tabs");
                });

            modelBuilder.Entity("Application.Models.Window", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<bool>("IsIncognito")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_incognito");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<int?>("Window")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Window");

                    b.ToTable("Windows");
                });

            modelBuilder.Entity("Application.Models.Tab", b =>
                {
                    b.HasOne("Application.Models.Window", null)
                        .WithMany("Tabs")
                        .HasForeignKey("Tab");
                });

            modelBuilder.Entity("Application.Models.Window", b =>
                {
                    b.HasOne("Application.Models.Session", null)
                        .WithMany("Windows")
                        .HasForeignKey("Window");
                });

            modelBuilder.Entity("Application.Models.Session", b =>
                {
                    b.Navigation("Windows");
                });

            modelBuilder.Entity("Application.Models.Window", b =>
                {
                    b.Navigation("Tabs");
                });
#pragma warning restore 612, 618
        }
    }
}
